server:
  port: 8082

spring:
  application:
    name: employee-service

  data:
    mongodb:
      uri: mongodb+srv://jaswanth:jaswanth1234!@mycluster1.wfk3b73.mongodb.net/employeeDb?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
